# Generated by Django 5.2.13 on 2026-04-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='complexity',
            field=models.IntegerField(default=1),
        ),
    ]
